sudo: required

services:
  - docker

env:
  matrix:
    - DOCKERFILE="master"
    - DOCKERFILE="8"
    - DOCKERFILE="7"
    - DOCKERFILE="6"

before_script:
  - docker version

script:
  - docker build -t ${DOCKERFILE} ./${DOCKERFILE}

after_script:
  - docker images
  - docker ps -a
