sudo: required

services:
  - docker

env:
  matrix:=
    - DOCKERFILE="Dockerfile" DOCKERPATH="6"
    - DOCKERFILE="Dockerfile-alpine" DOCKERPATH="6"
    - DOCKERFILE="Dockerfile" DOCKERPATH="7"
    - DOCKERFILE="Dockerfile-alpine" DOCKERPATH="7"
    - DOCKERFILE="Dockerfile" DOCKERPATH="8"
    - DOCKERFILE="Dockerfile-alpine" DOCKERPATH="8"
    - DOCKERFILE="Dockerfile" DOCKERPATH="master"
    - DOCKERFILE="Dockerfile-alpine" DOCKERPATH="master"

before_script:
  - docker version

script:
  - docker build -f ./${DOCKERPATH}/${DOCKERFILE} -t ${DOCKERPATH} ./${DOCKERPATH}

after_script:
  - docker images
