FROM php:7.3.27-cli-alpine
LABEL maintainer="digitalpulp"

RUN apk add --no-cache --virtual .dd-build-deps libpng-dev libjpeg-turbo-dev postgresql-dev libxml2-dev $PHPIZE_DEPS \
   && apk add --no-cache --update zlib libzip-dev \
   && docker-php-ext-configure gd --with-png-dir=/usr --with-jpeg-dir=/usr \
   && docker-php-ext-install gd mbstring pdo pdo_mysql pdo_pgsql zip \
   && docker-php-ext-install opcache bcmath soap \
   && docker-php-ext-configure intl && docker-php-ext-install intl \
   && pecl install redis-3.1.1 xdebug \
   && docker-php-ext-enable redis xdebug \
   && php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
   && php -r "if (hash_file('sha384', 'composer-setup.php') === '756890a4488ce9024fc62c56153228907f1545c228516cbf63f885e036d37e9a59d27d63f46af1d4d07ee0f76181c7d3') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" \
   && php composer-setup.php --install-dir=/usr/local/bin --filename=composer --version=1.10.20 \
   && php -r "unlink('composer-setup.php');" \
   && echo "export PATH=~/.composer/vendor/bin:\$PATH" >> ~/.bash_profile \
   && apk add --no-cache sudo git libpng libjpeg libpq libxml2 mysql-client openssh-client rsync patch expect \
   && apk del .dd-build-deps \
   && apk add --no-cache mysql-client openssh-client rsync \
   && apk add --no-cache bash bash-doc bash-completion

COPY drupal-*.ini /usr/local/etc/php/conf.d/
COPY xdebug.ini /usr/local/etc/php/conf.d/
COPY ssh-add.sh /root
COPY key-place.sh /root
RUN chmod 655 /root/ssh-add.sh && chmod 655 /root/key-place.sh

CMD ["tail", "-f", "/dev/null"]
