FROM php:7.1-alpine
LABEL maintainer="digitalpulp"

COPY pre-commit.sh /root
RUN apk add --no-cache --virtual .dd-build-deps libpng-dev libjpeg-turbo-dev postgresql-dev libxml2-dev $PHPIZE_DEPS \
   && docker-php-ext-configure gd --with-png-dir=/usr --with-jpeg-dir=/usr \
   && docker-php-ext-install gd mbstring pdo pdo_mysql pdo_pgsql zip \
   && docker-php-ext-install opcache bcmath soap \
   && pecl install redis-3.1.1 \
   && docker-php-ext-enable redis \
   && php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
   && php -r "if (hash_file('SHA384', 'composer-setup.php') === '544e09ee996cdf60ece3804abc52599c22b1f40f4323403c44d44fdfdd586475ca9813a858088ffbc1f233e9b180f061') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" \
   && php composer-setup.php \
   && php -r "unlink('composer-setup.php');" \
   && mv composer.phar /usr/local/bin/composer \
   && echo "export PATH=~/.composer/vendor/bin:\$PATH" >> ~/.bash_profile \
   && apk add --no-cache sudo git libpng libjpeg libpq libxml2 mysql-client openssh-client rsync \
   && apk del .dd-build-deps \
   && apk add --no-cache mysql-client openssh-client rsync \
   && apk add --no-cache bash bash-doc bash-completion \
   && apk add --no-cache python3 \
   && python3 -m ensurepip  \
   && rm -r /usr/lib/python*/ensurepip \
   && pip3 install --upgrade pip setuptools \
   && if [ ! -e /usr/bin/pip ]; then ln -s pip3 /usr/bin/pip ; fi \
   && if [[ ! -e /usr/bin/python ]]; then ln -sf /usr/bin/python3 /usr/bin/python; fi \
   && pip install pre-commit \
   && pre-commit install-hooks \
   && rm -r /root/.cache \
   && composer global require drush/drush:8.1.15 \
   && ln -s ~/.composer/vendor/bin/drush /usr/local/bin/drush \
   && drush core-status -y

COPY pre-commit.sh /usr/local/bin/
COPY drupal-*.ini /usr/local/etc/php/conf.d/
COPY xdebug.ini /usr/local/etc/php/conf.d/

RUN chmod ugo=rx /usr/local/bin/pre-commit.sh

CMD ["tail", "-f", "/dev/null"]
