FROM php:5.6.34-alpine
MAINTAINER digitalpulp

VOLUME /var/www

ENV PATH "/home/www-data/.composer/vendor/bin:${PATH}"

RUN apk add --no-cache --virtual .dd-build-deps libpng-dev libjpeg-turbo-dev postgresql-dev libxml2-dev $PHPIZE_DEPS \
   && docker-php-ext-configure gd --with-png-dir=/usr --with-jpeg-dir=/usr \
   && docker-php-ext-install gd mbstring pdo pdo_mysql pdo_pgsql zip \
   && docker-php-ext-install opcache bcmath soap \
   && pecl install redis-2.2.8 \
   && pecl install xdebug-2.5.4 \
   && docker-php-ext-enable redis xdebug\
   && php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
   && php -r "if (hash_file('SHA384', 'composer-setup.php') === '544e09ee996cdf60ece3804abc52599c22b1f40f4323403c44d44fdfdd586475ca9813a858088ffbc1f233e9b180f061') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" \
   && php composer-setup.php \
   && php -r "unlink('composer-setup.php');" \
   && mv composer.phar /usr/local/bin/composer \
   && echo "export PATH=~/.composer/vendor/bin:\$PATH" >> ~/.bash_profile \
   && apk add --no-cache sudo git libpng libjpeg libpq libxml2 mysql-client openssh-client rsync \
   && apk del .dd-build-deps \
   && apk add --no-cache mysql-client openssh-client rsync

COPY drupal-*.ini /usr/local/etc/php/conf.d/
COPY xdebug.ini /usr/local/etc/php/conf.d/

RUN chown -R www-data:www-data /var/www

USER www-data

RUN composer global require drush/drush:8.1.15 \
   && composer global config minimum-stability dev \
   && composer global config prefer-stable true \
   && composer global require drupal/console-launcher:1.0.2 \
   && drush core-status -y

CMD ["tail", "-f", "/dev/null"]
