FROM digitalpulp/cli:codeship
LABEL maintainer="digitalpulp"

RUN mkdir /var/www && chown -R www-data:www-data /var/www

ENV PATH "/var/www/vendor/bin:${PATH}"

USER www-data

VOLUME /var/www
ENTRYPOINT []
CMD ["tail", "-f", "/dev/null"]
